### ISSUE TITLE
Add editing functionality to the TBODeveloperOverlayNSUserDefaultsDatasource

### ISSUE THREAD

**Issue by brototyp** [tbointeractive/TBODeveloperOverlay#2]
I guess there are situations where I would want to edit values in the `NSUserDefaults`.

Points to consider:
- Should this be a functionality of the default TBODeveloperOverlayNSUserDefaultsDatasource or would the best way to subclass it and add the editing functionality?
- If implemented in the TBODeveloperOverlayNSUserDefaultsDatasource, how would we configure which keys are there to edit?

**Comment by thorstenstark** [comment]
What if we make all or none keys editable by initializing the datasource with an "isEditable" parameter?

**Comment by brototyp** [comment]
Hm. I guess that is quite a black-and-white solution. I can imagine situations where you only want to be able to edit certain values.

What do you think of this solution:
- per default the TBODeveloperOverlayNSUserDefaultsDatasource doesn't allow editing any fields
- one can implement a subclass and enable editing TBODeveloperOverlayNSUserDefaultsDatasource via -isEditableForIndexPath: for only certain values
- – didChangeValue:atIndexPath: is already implemented in the TBODeveloperOverlayNSUserDefaultsDatasource

**Comment by thorstenstark** [comment]
I like that idea.
