### ISSUE TITLE
Sharing the content from the LoggerOverlay

### ISSUE THREAD

**Issue by brototyp** [tbointeractive/TBODeveloperOverlay#4]
I guess it is a good idea to share the currently visible content from the logger overlay. Therefore one could easily copy the content or share it via e-mail or such.

Downside:
- This means (partially) duplicated functionality. Mostly the same functionality could be implemented by sharing via the FileInspector.

**Comment by thorstenstark** [comment]
But here you could share also the filtered log instead of only the full one.

**Comment by brototyp** [comment]
So, just add a share button and share the content of the NSTextField?

**Comment by thorstenstark** [comment]
Yes, that would be my proposal.
